App testing [sprint6/step1]
lunarkbot/react-burger pull request #8
Opened 2022-11-30 23:25 UTC by lunarkbot

### Brief
Added tests for the Redux store, as well as e2e tests for the user-order functionality.

- 57 unit tests for 7 Redux Toolkit Slices covering all reducers and thunks
- 4 Cypress tests from ingredient selection to order placement
- the application hosted on own domain and server: https://react-burger.kbot.page

2022-12-01 03:11 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Все юнит-тесты (57 шт) проходят успешно

### **Но есть несколько замечаний, которые нужно исправить:**

- Из компонента `BurgerIngredients` нужно убрать запрос ингредиентов с сервера. Вы уже делалете его в компоненте `App`. https://yadi.sk/d/XRPZ_k9Ml5Ykwg

- Исправьте ошибки связанные с Typescript, из-за этого проект может запускаться с ошибками.
  https://yadi.sk/d/Ab_h6fvEE5zq3w

- У вас падают cypress тесты, https://yadi.sk/d/vkqjEDXBOKt68Q.

- По чек-листу, в cypress вам нужно реализовать проверку всех модальных окон.

  У вас реализована проверка модального окна заказа.
  Нужно также реализовать проверку модального окна с описанием ингредиента.

  - открытие модального окна с описанием ингредиента,

  - отображение в модальном окне данных ингредиента,

### **Сделает код лучше:**

- Добавить команду запуска Cypress, в `package.json`,

  ```json
  "cypress:open": "./node_modules/.bin/cypress open"
  ```

- Чтобы проверить процент покрытия тестами всех компонентов используйте команду `react-scripts test --coverage --watchAll`.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-12-01 03:11 UTC, ArslanMustafin commented on src/services/__tests__/ingredientsSlice.test.ts
> +    // @ts-ignore
**Надо исправить:**

Здесь и далее, в других тестах.

Не стоит без необходимости использовать `@ts-ignore`, тут проблема заключаеться в функции fetch. 

Чтобы её исправить, достаточно указать явно тип `(fetch as jest.Mock)`, и всё заработает)

2022-12-01 03:11 UTC, ArslanDev666 commented on cypress/e2e/place-an-order.cy.ts
> +    cy.visit('http://localhost:3000');
**Можно лучше:**

Базовый `url` адрес лучше вынести вы константу

2022-12-01 03:11 UTC, ArslanDev666 commented on cypress/e2e/place-an-order.cy.ts
> +    cy.get('[data-testid="60d3b41abdacab0026a733c6"]').trigger("dragstart");
**Можно лучше:**

`id` ингредиентов лучше вынести вы константу, тоже самое касается и классов.

2022-12-02 03:59 UTC, ArslanDev666 commented
> @ArslanDev666 Есть одна проблема - я не могу воспроизвести ошибки TypeScript - проект запускается без ошибок. Пробовал даже склонировать репозиторий заново, пробовал склонировать на другой комп, на котором я не вел разработку этого проекта (так скажем чистая машина) - все равно нет ошибок. Как их вызвать, что исправить мне совсем не очевидно. upd: Вижу что на скрине проблема с компонентом Button, что идет от библиотеки Яндекса. Попробовал в package.json поставить ограничение до более свежей версии. Обновил пакет - все равно нет ошибок. Может теперь и у вас пропадут ¯\_(ツ)_/¯ upd2: А вот после обновления библиотеки Яндекса до актуальной стабильной версии + после перезапуска проекта появились ошибки. Сейчас исправлю =)

У меня сначала не ставились ваши версии пакетов, поэтому был удалён package-lock.json, и соответственно, некоторые пакеты обновились до новых версий.

2022-12-02 03:59 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.🔥

### **Вы молодец!**

- Все замечания с прошлого ревью были исправлены.

Несколько советов для дальнейшего развития:

- Сверстайте несколько небольших проектов для себя, для закрепления знаний, и чтобы можно добавить их в портфолио.

- Ходите на собеседования: опыт прохождения собеседований не менее важен знаний теории, и Вы поймете, какие знания требуются на рынке, и где Вы проседаете.

- Читайте habr и слушаете подкаксты: они очень хорошо расширяют кругозор и позволяют узнать, что происходит в отрасли.

### **Сделает код лучше:**

- В будущем тестируйте cypress в хроме) т.к. мы делаем больше веб-приложение, а не десктопное.

2022-12-02 10:04 UTC, ArslanDev666 commented
Всегда рад помочь)) 
1. я тестировал в хроме, и у меня ваши cypress тесты не проходили, а потом я попробовал протестировать на электроне, и всё прошло. Честно говоря, смотрел на ошибки, там (при тестировании в хроме) что-то связанное с cors было.

2. Взял список у своего коллеги, сам из этого всего, слушаю только веб-стандарты)) а также иногда смотрю JS-митапы по тем или иным технологиям.    

- https://soundcloud.com/everyonecan

- https://soundcloud.com/podlodka

- https://soundcloud.com/devschacht

- https://soundcloud.com/begebot

- https://soundcloud.com/web-standards

- https://www.youtube.com/channel/UCZeU17nbVfzczAkJVTay9vw

Плюс советую серьёзно взяться за алгоритмы и книги в целом: 
- Для начала можно прочесть книжку: Грокаем алгоритмы. Иллюстрированное пособие для программистов и любопытствующих [Адитья Бхаргава].
- А потом если всё хорошо пойдёт, то вот эту: https://www.r-5.org/files/books/computers/algo-list/common/Cormen_Leiserson_Rivest_Stein-Introduction_to_Algorithms-RU.pdf. Но она такая, сложненькая))
- Дэвид Флэнаган "JavaScript. Подробное руководство" - это уже чтобы углубиться в js. 
- Чистый код. Создание, анализ и рефакторинг. Мартин Роберт. - это больше для себя, не весь материал в книге широко используется, но знать полезно :)

2022-12-03 19:51 UTC, merged